weighted_alpaca_eval_dpsk_v3:
  prompt_template: "lmsys_gpt4/lmsys_prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "deepseek-v3-0324"
    max_tokens: 10
    temperature: 1 # temperature should be applied for sampling, so that should make no effect.
    num_procs: 10
  fn_completion_parser: "lmsys_parser"
  # fn_completion_parser: "regex_parser"
# fn_completion_parser: "logprob_parser"
  batch_size: 1
  is_randomize_output_order: false  # lmsys doesn't seem to randomize order
  # completion_parser_kwargs:
  #   numerator_token: "m"
  #   denominator_tokens: ["m", "M"]
  #   is_binarize: false
  # completion_key: "completions_all"
